### ISSUE TITLE
Building under Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rdbyk** [Nelson-numerical-software/nelson#118]
### Expected Behavior

Building of Nelson as described in [DEVELOPMENT.md](https://github.com/Nelson-numerical-software/nelson/blob/master/DEVELOPMENT.md)

### Actual Behavior

Builds fails, due to too old
- CMake
- Boost libraries

IMHO, it should be pointed out, that building under Ubuntu 14.04 LTS is not (at least easily) possible . Furthermore, there is a typo
```
cd Nelson
cmake -G "Unix Makefiles"
```
should be read as
```
cd nelson
cmake -G "Unix Makefiles"
```
### Steps to Reproduce (including precondition)

Follow build instructions given in  [DEVELOPMENT.md](https://github.com/Nelson-numerical-software/nelson/blob/master/DEVELOPMENT.md)

### Your Environment

- OS: Ubuntu 14.04 LTS
- Nelson version: current master

**Comment by Nelson-numerical-software** [comment]
feel free to comment.
You are welcome !
