### ISSUE TITLE
Execution of Simple Expression "1+2+3" is Rather Slow

### ISSUE THREAD

**Issue by rdbyk** [Nelson-numerical-software/nelson#119]
I am aware, that the project is in an early stage of development and it really looks very promising, but there seems to be a bottle neck which slows down the execution of simple expressions, e.g. "1+2+3", significantly ...

Nelson (current master)
```
--> tic;for i=1:1e5;1+2+3;end;toc
Elapsed time is 4.590101 seconds.
```
Scilab (current master)

```
--> tic;for i=1:1e5;1+2+3;end;toc
 ans  =

   0.079408
```

### Your Environment

- OS: Ubuntu 14.04 LTS
- Nelson version: current master

**Comment by Nelson-numerical-software** [comment]
Currently, in nelson, all types support overloading by default.

```
tic;for i=1:1e5;1+2+3;end;toc
```
it is equivalent to 
```
tic;for i=double_colon_double(1,1e5);double_plus_double(double_plus_double(1, 2), 3);end;toc
```

Some big optimizations and choices are to do for  version 1.0.0  (JIT).
overloading on double, char, integer are very interesting feature but it is also a bottle neck ...
A solution could be to have a "live configuration" command to allow or not overload on a type.
Nelson is very young and first versions are not oriented speed optimization but features.
If you want to have really speed see Julia ;)

**Comment by Nelson-numerical-software** [comment]
Your help is welcome to give an advice or propose some patchs or devs ;)

**Comment by Nelson-numerical-software** [comment]
other case
```
T = 0;
for i=1:1e5;
tic;1+2+3;t=toc();
T = T + t;
end
T * inv(1e5)
```

**Comment by Nelson-numerical-software** [comment]
To speed up Nelson, it should be possible to add a function: overloading
by default overloading should be disabled on double, integers, sparse, char, logical

```
overloading('double', true) will enable overloading on 'double'
overloading('double') will return current state
```
Currently for example '+' operator calls (with interpreter evaluation) 'plus' function. 'plus' function calls (with interpreter evaluation)  type_plus_type function.
overloading function will modify this behaviour: '+' will call directly without evaluation type_plus_type code

It is not a small modification. A branch with a basic test only on double type need to be created before to apply it on all major types of Nelson.

**Comment by Nelson-numerical-software** [comment]
Open question:
Do we allow overload on operators with basic types ?

Currently, nelson allows it on all types. BUT it can be definitively dangerous if a user redefine a operator for basic types. It is also very time consuming ...

bench on my pc: with overload (currently on nelson)
--> tic;for i=1:1e5;1+2+3;end;toc
Elapsed time is 3.639208 seconds.

without overload double + double (without other optimisation)
--> tic;for i=1:1e5;1+2+3;end;toc
Elapsed time is 0.368959 seconds.

Maybe cannot allow overload for operators with same basic types in a first step
double + double ==> hardcoded function 
double + single ==> overload
...

**Comment by rdbyk** [comment]
IMHO, all obviously and commonly defined operations should be hardcoded for all basic types.
Only not so common coperations, e.g. double + string, string / string ..., should be overloaded.

**Comment by Nelson-numerical-software** [comment]
see PR #126 (in progress)
after this PR some others optimization will be required about for loop (in another issue)

**Comment by Nelson-numerical-software** [comment]
merged in master
