### ISSUE TITLE
Function of "Pos1" Key in "nelson-gui" Console

### ISSUE THREAD

**Issue by rdbyk** [Nelson-numerical-software/nelson#121]
**Describe the bug**
Pressing Pos1 key makes the cursor jump to very beginning of the promp "-->" and not
to the beginning of the entered command line.

**To Reproduce**
Just press Pos1 Key ... and watch

**Expected behavior**
Cursor should jump to the first position of the entered command

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04 LTS

**Comment by Nelson-numerical-software** [comment]
Feel free to propose a patch if you need :)
