### ISSUE TITLE
Undocumented Keyword "parfor"

### ISSUE THREAD

**Issue by rdbyk** [Nelson-numerical-software/nelson#131]
**Describe the bug**
Not a big issue, there seems to be an undocumented alias `parfor` for the keyword `for` ... but even small left-overs tend to pile up over the years :wink:  

**To Reproduce**
```
--> parfor i=1:3,disp(i),end
  1
  2
  3
--> for i=1:3,disp(i),end
  1
  2
  3
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04
 - Version 0.2.5.0

**Comment by Nelson-numerical-software** [comment]
Thanks !!!
some others missing keywords not documented:
// abort
// break
// case
// catch
// continue
// else
// elseif
// endfunction
// otherwise
// return
// switch
// try
// while
