### ISSUE TITLE
Replace Uncommon Term "Trinary" by "Ternary" (Cosmetics)

### ISSUE THREAD

**Issue by rdbyk** [Nelson-numerical-software/nelson#133]
**Describe the bug**
search for [Trinary](https://github.com/Nelson-numerical-software/nelson/search?q=Trinary&unscoped_q=Trinary) in the repo.

IMHO "trinary" should be replaced by "ternary", it seems that "trinary" is correct as well, but it is not commonly used.

**Comment by Nelson-numerical-software** [comment]
fixed in overloading branch
Thanks

**Comment by Nelson-numerical-software** [comment]
merged in master
