### ISSUE TITLE
Evaluation of Non-Scalar If-Condition Expression

### ISSUE THREAD

**Issue by rdbyk** [Nelson-numerical-software/nelson#134]
**Describe the bug**

I am not sure, whether the following is intentional, but I think it is a bug. Only if **all** elements of a non-scalar `if`-condition are `true`, then the `then` statement should be executed?

```
--> if [false,false],disp('TRUE'),else,disp('FALSE'),end
FALSE
--> if [true,false],disp('TRUE'),else,disp('FALSE'),end
TRUE % Not OK, should be FALSE
--> if [false,true],disp('TRUE'),else,disp('FALSE'),end
TRUE % Not OK, should be FALSE
--> if [true,true],disp('TRUE'),else,disp('FALSE'),end
TRUE
```

 - OS:  Ubuntu 14.04
 - Version 0.2.5.0

**Comment by Nelson-numerical-software** [comment]
it is a bug (I forgot to manage this case)...
Thanks
