### ISSUE TITLE
colon operator does not return expected for non scalar element

### ISSUE THREAD

**Issue by rdbyk** [Nelson-numerical-software/nelson#138]
**Describe the bug**
```
--> [1 2]:2
Expected a real value scalar.
called from:
EvaluateString
at line: 1 position: 7

--> (1:2):2

ans =

     1     0  // Not OK, should raise an error, cf. above
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04
 - Version 0.2.50

**Comment by Nelson-numerical-software** [comment]
In fact, these two test cases are wrong:
-  [1 2]:2 should return 1:2
-  (1:2):2 should return  1:2
- [1 2; 3 4]:2 should return  1:2

colon operator need to take first element if it is not scalar.


Thanks

**Comment by Nelson-numerical-software** [comment]
[2:4]:[3:5]:[6:7] should return [2 5]

**Comment by rdbyk** [comment]
What is the rationale for these two cases?

- [1 2]:2 should return 1:2
- [1 2; 3 4]:2 should return 1:2

Is it, that from non-scalar args only the first element is used? If yes, I think it would be better not to allow non-scalar args and raise an error here. just my opionion ...

**Comment by Nelson-numerical-software** [comment]
to be compatible or not ? it is a hard question :(
octave versus julia ...
The problem is also about empty matrix.
Manages empty matrix requires also to manage matrix, vector, scalar.
A warning could be added to warn a wrong size

**Comment by rdbyk** [comment]
A warning seems to be a reasonable compromise ...

**Comment by Nelson-numerical-software** [comment]
warning id 'Nelson:colon:vector-as-scalar' will be added. Enabled by default

**Comment by Nelson-numerical-software** [comment]
[]:3 must also return a vector 1x0
zeros(0,4):3  must also return a vector 1x0

**Comment by Nelson-numerical-software** [comment]
![image](https://user-images.githubusercontent.com/23081266/43687942-6e2c916c-98df-11e8-9eac-cf7d7dd8b665.png)
