### ISSUE TITLE
[Documentation request]  comparison with other MATLAB alternatives

### ISSUE THREAD

**Issue by Foadsf** [Nelson-numerical-software/nelson#604]
My new company has a very limited number of MATLAB licenses and I want to suggest one of the FLOSS alternatives as an intermediary solution. The common alternatives that conform to the MATLAB syntax are:

* [GNU Octave](https://www.gnu.org/software/octave/index)
* [FreeMat](http://freemat.sourceforge.net/)
* Nelson Numerical software
* [OpenMatrix Language (OML)](https://www.openmatrix.org/)

I am not considering Scilab and [its many forks](https://www.reddit.com/r/math/comments/b6gn9r/nsp_is_a_gpl_scientific_software_package/), even though no other FLOSS out there offers a better [SIMULINK alternative](https://qr.ae/pGjKGA) than xcos/scicos. Mainly because the language is not fully MATLAB compliant. 

From the above four, FreeMat and OML are practically dead. Now [here](https://userpages.umbc.edu/~gobbert/papers/SharmaGobbertTR2010.pdf) Sharma et. al. has provided a relatively good comparison between the FLOSS alternatives Octave, FreeMat, and Scilab. It would be great if you could add a Nelson comparison as well.

**Comment by Nelson-numerical-software** [comment]
Nelson is "young" and have again some major missing features ( standard plot methods, compatible overload features, control module , ode, optimization)

I hope to propose a 1.0 in 2 years (if I continue with this good rythm)
(this year: overload, control and ode)

For Simulink alternative, It is something that I already thought (I participated to Scicos/Xcos and also another commercial version). 

But time is not yet come ;) without more external helps ...

Contributors are Welcome !!! 

P.S.
I will try to contact Neeraj Sharma and Matthias K. Gobbert to ask to consider Nelson.

**Comment by Nelson-numerical-software** [comment]
Close ticket until nelson is not available as 1.0 (expected end 2023)
plots support available in 0.6.12 (i hope) and control with 0.7.2

Help is welcome !!!
