### ISSUE TITLE
[Package request] Chocolatey package manager for Windows

### ISSUE THREAD

**Issue by Foadsf** [Nelson-numerical-software/nelson#605]
It would be great if you could add Nelson to the [Chocolatey package manager](https://chocolatey.org/).

**Comment by Foadsf** [comment]
You may also want to update the [Repology entry for Nelson](https://repology.org/project/nelson/versions). It doesn't seem to be uptodate.

**Comment by Foadsf** [comment]
I see that there is a winget package for Nelson and I am aware of the PortableApps package as well. Though Chocolatey package would be a great addition for the windows users IMHO.

**Comment by Nelson-numerical-software** [comment]
Propably for 0.6.4 (end of april)

**Comment by Nelson-numerical-software** [comment]
> You may also want to update the [Repology entry for Nelson](https://repology.org/project/nelson/versions). It doesn't seem to be uptodate.

I was happy to see that Nelson was packaged for Fedora by @bluebat
I sent a private email to him to have feedback and help for Fedora package

**Comment by Nelson-numerical-software** [comment]
https://community.chocolatey.org/packages/nelson in progress

**Comment by Nelson-numerical-software** [comment]
0.6.2 is available as `Ready for review`
0.6.3 will be normaly available as supported package in Chocolatey

I will create a script after to push automaticaly

**Comment by bluebat** [comment]
> > You may also want to update the [Repology entry for Nelson](https://repology.org/project/nelson/versions). It doesn't seem to be uptodate.
> 
> I was happy to see that Nelson was packaged for Fedora by @bluebat I sent a private email to him to have feedback and help for Fedora package

A new and workable package is at https://github.com/rpmsphere/x86_64/raw/master/n/nelson-0.6.2-1.x86_64.rpm
Install tricks are in nelson.spec in https://github.com/rpmsphere/source/raw/master/n/nelson-0.6.2-1.src.rpm
A test script is https://github.com/bluebat/mt9x9/raw/master/mt9x9.nlf

**Comment by Nelson-numerical-software** [comment]
> > > You may also want to update the [Repology entry for Nelson](https://repology.org/project/nelson/versions). It doesn't seem to be uptodate.
> > 
> > 
> > I was happy to see that Nelson was packaged for Fedora by @bluebat I sent a private email to him to have feedback and help for Fedora package
> 
> A new and workable package is at https://github.com/rpmsphere/x86_64/raw/master/n/nelson-0.6.2-1.x86_64.rpm Install tricks are in nelson.spec in https://github.com/rpmsphere/source/raw/master/n/nelson-0.6.2-1.src.rpm A test script is https://github.com/bluebat/mt9x9/raw/master/mt9x9.nlf

@bluebat Thanks for you Help :)
