### ISSUE TITLE
Dark mode - title bar theme no more applied

### ISSUE THREAD

**Issue by Nelson-numerical-software** [Nelson-numerical-software/nelson#940]
Bug detected by @Spationaute

Can be reproduce on Windows 10, 11

![image](https://github.com/Nelson-numerical-software/nelson/assets/23081266/2c227528-7bfd-4129-b14c-b93581d2768e)

It seems to be a regression
![image](https://github.com/Nelson-numerical-software/nelson/assets/23081266/ae40c9ea-be61-4619-af79-d11a8d76ca5a)

**Comment by Nelson-numerical-software** [comment]
With Qt 5.x same version works as expected
![image](https://github.com/Nelson-numerical-software/nelson/assets/23081266/34987e7f-49f5-4fa0-8d56-ca9b7581acef)

Code using Qt 6 need to be updated

**Comment by Spationaute** [comment]
There is also the white on grey text in the help. 

![image](https://github.com/Nelson-numerical-software/nelson/assets/3812694/8bf42e2c-6ccf-431e-80f7-581d77a8981b)

And the label out of bound for the graph. 
![image](https://github.com/Nelson-numerical-software/nelson/assets/3812694/94a428b4-c9f3-4001-bfa9-a81b88b78df0)

**Comment by Nelson-numerical-software** [comment]
should be fixed in next version
![image](https://github.com/Nelson-numerical-software/nelson/assets/23081266/5c101a22-fff2-4be1-a256-29d64380837d)
