### ISSUE TITLE
Loss of precision when converting 64-bit integers

### ISSUE THREAD

**Issue by Lokinyx** [Nelson-numerical-software/nelson#980]
>> intmax("int64")

ans =

  int64

   9223372036854775807

>> int64(81997179153022975)

ans =

  int64

   81997179153022976

>> int64(81997179153022976)

ans =

  int64

   81997179153022976

>> int64(81997179153022977)

ans =

  int64

   81997179153022976

we can see some precision lost for 81997179153022977 and 81997179153022975 when converted to int64.

**Comment by Nelson-numerical-software** [comment]
Try this on any numerical tools, there is a loss of precision

```matlab
int64(double(int64(81997179153022977)))
```
or 
```matlab
uint64([81997179153022977, 81997179153022979])
```
Many software apply tricks to convert but it is not never perfect. except if double replaced by long double

Keep in mind that double-precision floating-point numbers have limited precision, and there's always a limit to how accurately they can represent large integer

bigger int as double without precision trouble: 9007199254740992

To do:
- implement flintmax function
- add warning about conversion lost 
- we can extend syntax to convert directly to int type
example:
81997179153022977u64
81997179153022977i64

with u64, u32, u16, u8, i64, i32, i16, i8,

with this syntax, it will possible to do:
![image](https://github.com/Nelson-numerical-software/nelson/assets/23081266/f0226ca0-d339-421e-881b-1c3ebb40c466)

it will not break compatibility and allow to easily manage big integer in Nelson

@Lokinyx what is your opinion about this syntax ?

**Comment by Nelson-numerical-software** [comment]
Proposed warning:
![image](https://github.com/Nelson-numerical-software/nelson/assets/23081266/e2262642-1eba-4c36-b4ba-ffeab1c6f2b6)

**Comment by Nelson-numerical-software** [comment]
feature added in 0.7.10
